### ISSUE TITLE
Removes multiple items with the same priority, regardless of test

### ISSUE THREAD

**Issue by andrewKyres** [luanpotter/ordered_set#2]
If a test would remove a single item, it instead removes all items in that priority bucket.

**Comment by luanpotter** [comment]
According to the docs:

```
  /// Remove a single element that is equal to [e].
  ///
  /// If there are multiple elements identical to [e], only the first will be removed.
  /// To remove all, use something like:
  ///
  ///     set.removeWhere((a) => a == e);
  ///
  bool remove(E e) { ... }
```

So what method are you using (remove, or removeWhere)?

Because it might be expected. Would you like to contribute with a PR with a test case that fails describing your scenario?

**Comment by andrewKyres** [comment]
I'm using removeWhere. I'll return to this issue after the other one.
